[package]
name = "py32csdk-hal-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.69"
cc = "1.0"
glob = "0.3"


[features]
default = ["recompile","py32_0-A"]
recompile = ["regenerate-bindings"]
regenerate-bindings = []
py32_0-A = []